version: "3"

services:
  database:
    image: postgres:10.5
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  redis:
    image: redis:5.0
    ports:
      - "6379:6379"
  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - bundle-volume:/usr/local/bundle
      - .:/reminder-boy
    ports:
      - "3000:3000"
    depends_on:
      - database
      - redis
    tty: true
    stdin_open: true

volumes:
  bundle-volume:
    driver: local
