version: "3"

services:
  database:
    image: postgres:10.5
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  redis:
    image: redis:5.0
    ports:
      - "6379:6379"
  web: &web_base
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - bundle-volume:/usr/local/bundle
      - .:/reminder-boy
    ports:
      - "3000:3000"
    depends_on:
      - database
      - redis
    tty: true
    stdin_open: true
  worker:
    <<: *web_base
    command: bundle exec sidekiq
    ports: []
  webpack:
    <<: *web_base
    command: bin/webpack-dev-server
    ports:
      - "3035:3035"
    depends_on:
      - web
    tty: false
    stdin_open: false

volumes:
  bundle-volume:
    driver: local
