default: &default
  adapter: postgresql
  encoding: unicode
  host: database
  username: postgres
  password:
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: reminder-boy_development

test:
  <<: *default
  database: reminder-boy_test

production:
  <<: *default
  database: reminder-boy_production
  username: reminder-boy
  password: <%= ENV['REMINDER-BOY_DATABASE_PASSWORD'] %>
